# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TreenApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TreenAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end








# React Native 프로젝트의 Podfile

# # iOS 최소 지원 버전
# min_ios_version_supported = "12.0" 
# platform :ios, min_ios_version_supported

# # React Native 프로젝트 준비
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# prepare_react_native_project!

# # 링크 방식 설정
# linkage = ENV['USE_FRAMEWORKS']
# if linkage
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# # 프로젝트 설정
# target 'TreenApp' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   target 'TreenAppTests' do
#     inherit! :complete
#   end

#   # Post-install 스크립트
#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       mac_catalyst_enabled: false
#     )
#     # Apple Silicon 환경에서 시뮬레이터 빌드 문제 해결
#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
#         config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#       end
#     end
#   end
# end
